services:
  task-nest:
    build:
      context: .
      dockerfile: ./apps/task-nest/Dockerfile
      target: development
    env_file:
      - ./apps/task-nest/.env
      
    command: pnpm run start:dev task-nest
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uc

